name: 'hospital_analytics'
version: '1.0.0'
config-version: 2
profile: 'hospital'
model-paths: ["models"]
models:
  hospital_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table