version: 2
sources:
  - name: public
    tables:
      - name: appointments
      - name: treatments
      - name: billing

models:
  - name: fact_appointments
    columns:
      - name: appointment_id
        tests: [not_null, unique]
      - name: patient_id
        tests: [not_null]
      - name: doctor_id
        tests: [not_null]
      - name: payment_status
        tests:
          - accepted_values:
              values: ['Pending','Paid','Partial','Waived']