name: 'hospital_dbt'
version: '1.0.0'
config-version: 2

profile: 'hospital_dbt'

model-paths:  ["models"]
test-paths:   ["tests"]
macro-paths:  ["macros"]

target-path:  "target"
clean-targets: ["target", "dbt_packages"]

models:
  hospital_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
