name: CI — lint and test
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install sqlfluff
      - run: sqlfluff lint sql/advanced_queries.sql sql/schema.sql --dialect postgres --exclude-rules ST02,ST06,ST07,AL01,LT05,LT12,LT01,LT02,RF04,LT13,LT15,CP05,LT04,AM05,AM03

  dbt-test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install dbt-postgres
      - run: mkdir -p ~/.dbt && cp dbt_project/profiles.yml ~/.dbt/profiles.yml
      - run: dbt deps
        working-directory: dbt_project
      - run: dbt run
        working-directory: dbt_project
      - run: dbt test
        working-directory: dbt_project
